apiVersion: v1
kind: ConfigMap
metadata:
  name: heat-diffusion-config-v3
data:
  cxmate.json: |
    {
      "general": {
        "location": "0.0.0.0:80",
        "logger": {
          "debug": true
        },
        "readTimeout": 9223372036854775807,
        "writeTimeout": 9223372036854775807
      },
      "service": {
        "location": "localhost:8080",
        "title": "heat-diffusion",
        "version": "3.0.0",
        "author": "Daniel Carlin",
        "summary": "Accepts a network with node heats, and propogates the heat along edges to create a new heat layout",
        "license": "MIT",
        "language": "Python",
        "parameters": [
          {
            "name": "time",
            "default": "0.1",
            "description": "The upper bound on the exponential multiplication performed by diffusion",
            "type": "number"

          },
          {
            "name": "normalize_laplacian",
            "default": "False",
            "description": "If True, will create a normalized laplacian matrix for diffusion",
            "type": "boolean"
          },
          {
            "name": "input_attribute_name",
            "default": "diffusion_input",
            "description": "The key diffusion will use to search for heats in the node attributes with"
          },
          {
            "name": "output_attribute_name",
            "default": "diffusion_output",
            "description": "Will be the prefix of the _rank and _heat attriubtes created by diffusion"
          }
        ],
        "singletonInput": true,
        "input": [
          {
            "label": "Input",
            "description": "An input network with heat values attached to nodes",
            "aspects": ["nodes", "edges", "nodeAttributes"]
          }
        ],
        "singletonOutput": true,
        "output": [
          {
            "label": "Output",
            "description": "An output network with new heats and a rank attribute created by diffusion",
            "aspects": ["nodes", "edges", "nodeAttributes"]
          }
        ]
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: heat-diffusion-service-v3
  annotations:
    external-dns.alpha.kubernetes.io/hostname: v4.heat-diffusion.cytoscape.io.
spec:
  ports:
    - name: http
      port: 80
      targetPort: cxmate-http
  selector:
    app: heat-diffusion
    version: v3
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heat-diffusion-deployment-v3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heat-diffusion
        version: v3
    spec:
      containers:
      - name: heat-diffusion
        imagePullPolicy: Always
        image: ericsage/heat-diffusion
        ports:
          - name: diffusion-http
            containerPort: 8080
      - name: cxmate
        imagePullPolicy: Always
        image: cxmate/cxmate
        ports:
          - name: cxmate-http
            containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /cxmate
      volumes:
        - name: config-volume
          configMap:
            name: heat-diffusion-config-v3
