apiVersion: v1
kind: Secret
metadata:
  name: storage-secret-v1
data:
  #minio_access_key: 130SEM0PG41YMEV9ZLHR
  minio_access_key: MTMwU0VNMFBHNDFZTUVWOVpMSFI=
  #minio_secret_key: oEHlqLDRmGnaajou6RW1rTet6Ub8x+iMk6bYs91z
  minio_secret_key: b0VIbHFMRFJtR25hYWpvdTZSVzFyVGV0NlViOHgraU1rNmJZczkxeg==
---
apiVersion: v1
kind: Service
metadata:
  name: storage-service-v1
  annotations:
    external-dns.alpha.kubernetes.io/hostname: v1.storage.cytoscape.io.
spec:
  ports:
    - name: http
      port: 80
      targetPort: minio-http
  selector:
    app: storage
    version: v1
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage-deployment-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: storage
        version: v1
    spec:
      containers:
      - name: minio
        image: minio/minio
        args:
          - server
          - /store
        env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: storage-secret-v1
                key: minio_access_key
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: storage-secret-v1
                key: minio_secret_key
        ports:
        - name: minio-http
          containerPort: 9000
        volumeMounts:
        - name: minio-volume
          mountPath: /store
      volumes:
      - name: minio-volume
        gcePersistentDisk:
          pdName: minio-object-store
          fsType: ext4

